# Generated by Django 5.2 on 2025-06-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_rename_created_at_chatmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='user',
        ),
    ]
