# Generated by Django 5.2 on 2025-06-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_eventtype_rename_organizer_event_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
