# Generated by Django 5.2 on 2025-06-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_delete_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
