# Generated by Django 5.2 on 2025-06-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_event_event_type_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
