# Generated by Django 5.2 on 2025-06-05 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_userpreference_created_at'),
    ]

    operations = [

        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='event_type',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventtype'),
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'event_type', 'created_at')},
        ),
    ]
