# Generated by Django 5.2 on 2025-06-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_userpreference_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'event_type')},
        ),
    ]
