# Generated by Django 5.2 on 2025-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_userpreference_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
    ]
