# Generated by Django 5.2 on 2025-06-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_event_popularity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.ticketclass'),
        ),
        migrations.AlterField(
            model_name='ticketclass',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketclasses', to='events.event'),
        ),
    ]
