# Generated by Django 5.2 on 2025-06-06 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_ticket_ticket_class_alter_ticketclass_event'),
    ]

    operations = [

        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='target_group',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='usage_limit',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='limit_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='max_usage',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='min_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_discounts', to=settings.AUTH_USER_MODEL),
        ),

        migrations.AddField(
            model_name='discountcode',
            name='discount_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_types', to='events.discounttype'),
        ),
        migrations.DeleteModel(
            name='TicketDiscount',
        ),
    ]
