# Generated by Django 5.2 on 2025-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_customergroup_discounttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('spending_goal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
