# Generated by Django 5.2 on 2025-06-06 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_customergroup_remove_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='groups',
            field=models.ManyToManyField(related_name='discount_codes', to='events.customergroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.customergroup'),
        ),
    ]
