# Generated by Django 5.2 on 2025-06-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_alter_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='discount_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.discounttype'),
        ),
    ]
