# Generated by Django 5.2 on 2025-06-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_remove_discountcode_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_types', to='events.discounttype'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
