# Generated by Django 5.2 on 2025-06-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_paymentvnpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvnpay',
            name='order_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
