# Generated by Django 5.2 on 2025-06-12 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_remove_chatroom_event_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventtype'),
        ),
    ]
