# Generated by Django 5.2 on 2025-06-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
